### ISSUE TITLE
导入入门级Demo出现报错。

### ISSUE THREAD

**Issue by Lzy9743** [SaiTingHu/HTFrameworkDemo#1]
将HTFramework（v0.1.5）导入一个新建的空工程，然后下载解压入门级Demo导入，提示“Assets\HTFrameworkDemo\Script\CustomModule\TimeModule.cs(84,30): error CS0115: 'TimeModule.OnResume()': no suitable method found to override“。在“TimeModule”继承的”CustomModuleBase“中手动加上“OnResume”虚方法后。提示”Assets\HTFrameworkDemo\Script\Debug\DebugTest.cs(16,13): error CS0246: The type or namespace name 'MonitorData' could not be found (are you missing a using directive or an assembly reference?)“

**Comment by SaiTingHu** [comment]
请注意，Demo仅支持 HTFramework(Latest version) 最新版，这在README中有说明，必须导入 HTFramework 的最新版，如果最新版没有发布，则导入最后一次git提交的版本。
