### ISSUE TITLE
求助！不能using System.Runtime.Remoting.Messaging;

### ISSUE THREAD

**Issue by gxh1996** [SaiTingHu/HTFrameworkDemo#2]
Unity2020.3.13
![image](https://user-images.githubusercontent.com/48506232/149668512-42b32ca9-1a09-43fb-9027-1c6994c25a5c.png)

![image](https://user-images.githubusercontent.com/48506232/149668361-44cb8b24-e155-4fa0-b551-f9779817a60f.png)
![image](https://user-images.githubusercontent.com/48506232/149668365-a25ce32a-45e4-40d7-b78f-4c3cceee624c.png)
![image](https://user-images.githubusercontent.com/48506232/149668379-c5e2a93c-09d2-4395-9909-a878a5bd6a0b.png)
我添加了`System.Runtime.Remoting`的引用，但发现下面没有`System.Runtime.Remoting.Messaging;`
![image](https://user-images.githubusercontent.com/48506232/149668439-a39c611e-7ab2-4cd2-a994-c94753153512.png)
咋弄！

**Comment by SaiTingHu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SaiTingHu/HTFrameworkDemo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 凌晨0:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SaiTingHu/HTFrameworkDemo] 求助！不能using System.Runtime.Remoting.Messaging; (Issue #2)





 
Unity2020.3.13
 
 

 
 
 我添加了System.Runtime.Remoting的引用，但发现下面没有System.Runtime.Remoting.Messaging;
 
 咋弄！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gxh1996** [comment]
解决方法：Api Compatibility Level
![image](https://user-images.githubusercontent.com/48506232/149719843-0ea65b83-7246-462a-a7aa-ed07c809eee8.png)
